# Generated by Django 5.1.5 on 2025-01-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.TextField()),
                ('exchanges_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_ApiData', to='main.exchanges')),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency_pairs', to='main.currency')),
                ('exchanges_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_TradingPair', to='main.exchanges')),
                ('quote_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_currency_pairs', to='main.currency')),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ask', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_bid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchanges_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_PriceData', to='main.exchanges')),
                ('pair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='main.tradingpair')),
            ],
        ),
    ]
