# Generated by Django 5.2a1 on 2025-01-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ask', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_bid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchanges_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_price_data', to='main.exchanges')),
                ('pair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_price_data', to='main.tradingpair')),
            ],
        ),
    ]
